name: wget-for-windows CI

on:  
  push:  
  pull_request:  
  workflow_dispatch:
  schedule:  
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      matrix:
        bits: [64]
        ftype: [wintls-static-lite,openssl-lite]
      fail-fast: false
    name: wget-wintls
    runs-on: windows-latest
    env:
      mingw: mingw${{matrix.bits}}
      build_type: ${{matrix.ftype}}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up ENVs for MSYS2 to inherit
      shell: bash
      run: |
        arch="x86_64"
        BRoot="${PWD}"
        BDir="build/${build_type}/${mingw}"
        CDir="${BDir}-config"
        echo arch="$arch" >> $GITHUB_ENV
        echo BRoot="$BRoot" >> $GITHUB_ENV
        echo BDir="$BDir" >> $GITHUB_ENV
        echo CDir="$CDir" >> $GITHUB_ENV

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{env.mingw}}
        release: false
        install: >-
          base-devel
          gperf
          autoconf
          automake
          autoconf-archive
          git
          python
          libcares-devel
          mingw-w64-${{env.arch}}-gcc
          mingw-w64-${{env.arch}}-gettext
          mingw-w64-${{env.arch}}-openssl

    - name: Install dependencies for wget-openssl
      run: |
        if [ "${{matrix.ftype}}" = "openssl-lite" ]; then
          wget -O- https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.50.tar.gz | tar xz
          cd libgpg-error-* || exit
          ./configure \
          --host=x86_64-w64-mingw32 \
          --disable-shared \
          --prefix="$BRoot/$BDir" \
          --enable-static \
          --disable-doc
          make -j$(nproc)
          make install
          cd ..

          wget -O- https://gnupg.org/ftp/gcrypt/libassuan/libassuan-3.0.1.tar.bz2 | tar xj
          cd libassuan-* || exit
          ./configure \
          --host=x86_64-w64-mingw32 \
          --disable-shared \
          --prefix="$BRoot/$BDir" \
          --enable-static \
          --disable-doc \
          --with-libgpg-error-prefix="$BRoot/$BDir"
          make -j$(nproc)
          make install
          cd ..
          
          wget -O- https://gnupg.org/ftp/gcrypt/gpgme/gpgme-1.23.2.tar.bz2 | tar xj
          cd gpgme-* || exit
          env PYTHON=/usr/bin/python3.11 ./configure \
          --host=x86_64-w64-mingw32 \
          --disable-shared \
          --prefix="$BRoot/$BDir" \
          --enable-static \
          --with-libgpg-error-prefix="$BRoot/$BDir" \
          --disable-gpg-test \
          --disable-g13-test \
          --disable-gpgsm-test \
          --disable-gpgconf-test \
          --disable-glibtest \
          --with-libassuan-prefix="$BRoot/$BDir"
          make -j$(nproc)
          make install
          cd ..
          wget -O- https://github.com/libexpat/libexpat/releases/download/R_2_6_2/expat-2.6.2.tar.gz | tar xz
          cd expat-* || exit
          ./configure \
          --host=x86_64-w64-mingw32 \
          --disable-shared \
          --prefix="$BRoot/$BDir" \
          --enable-static \
          --without-docbook \
          --without-tests \
          --with-libgpg-error-prefix="$BRoot/$BDir"
          make -j$(nproc)
          make install
          cd ..
  
          wget -O- https://github.com/metalink-dev/libmetalink/releases/download/release-0.1.3/libmetalink-0.1.3.tar.gz | tar xz
          cd libmetalink-* || exit
          EXPAT_CFLAGS="-I$BRoot/$BDir/include" \
          EXPAT_LIBS="-L$BRoot/$BDir/lib -lexpat" \
          ./configure \
          --host=x86_64-w64-mingw32 \
          --disable-shared \
          --prefix="$BRoot/$BDir" \
          --enable-static \
         --with-libgpg-error-prefix="$BRoot/$BDir" \
          --with-libexpat
          make -j$(nproc)
          make install
          cd ..
          
          wget -O- https://github.com/c-ares/c-ares/releases/download/v1.32.2/c-ares-1.32.2.tar.gz | tar xz
          cd c-ares-* || exit
          CPPFLAGS="-DCARES_STATICLIB=1" \
          ./configure \
          --host=x86_64-w64-mingw32 \
          --disable-shared \
          --prefix="$BRoot/$BDir" \
          --enable-static \
          --disable-tests \
          --disable-debug
          make -j$(nproc)
          make install
          cd ..
        fi  
        
    # 克隆指定的仓库
    - name: Clone wget repository
      run: git clone --branch openssl-test https://github.com/lifenjoiner/wget-for-windows.git wget

    - name: Generate configure
      run: |
        cd wget # 进入克隆的仓库目录
        ./bootstrap --skip-po
        sed -i "s/-dirty\b//p" configure

    - name: Install win-iconv (Build)
      run: |
        wget -O- https://github.com/win-iconv/win-iconv/archive/refs/tags/v0.0.8.tar.gz | tar xz
        cd win-iconv-0.0.8
        make -E CFLAGS=-Os prefix=/$mingw install
        cd ..

    - name: configure
      run: |
        mkdir -p $BDir
        mkdir -p $CDir
        cd $CDir
        export CFLAGS+=" -Wall -DGNULIB_defined_ESOCK -DSite=https://github.com/lifenjoiner/wget-for-windows"
        if [ "${{matrix.ftype}}" = "wintls-static-lite" ]; then
          CFLAGS+=" -D_WIN32_WINNT=0x0600 -Os" LDFLAGS="-static -s" $BRoot/wget/configure --prefix=$BRoot/$BDir --disable-debug --disable-rpath --disable-nls --without-libpsl --without-metalink --disable-pcre --disable-pcre2 --with-winidn --enable-threads=windows
        elif [ "${{matrix.ftype}}" = "openssl-lite" ]; then
          CFLAGS+=" -Os" LDFLAGS="-static -s" $BRoot/wget/configure --prefix=$BRoot/$BDir --with-ssl=openssl --disable-debug --disable-rpath --disable-nls --without-libpsl --without-metalink --disable-pcre --disable-pcre2 --with-winidn --enable-threads=windows
        fi

    - name: Build
      run: |
        cd $CDir
        echo -e "all:\n\n" > gnulib_po/Makefile
        make -j$(nproc)
        strip ${PWD}/src/wget.exe
        cp -fv ${PWD}/src/wget.exe ${PWD}/src/wget-${{matrix.ftype}}.exe

    - name: Show compiled wget info
      run: |
        ls -l $CDir/src/wget-${{matrix.ftype}}.exe
        SHA=$(sha1sum $CDir/src/wget-${{matrix.ftype}}.exe | cut -b 1-40)
        echo SHA="$SHA" >> $GITHUB_ENV
        $CDir/src/wget -V

    - name: Upload wget
      uses: actions/upload-artifact@v4
      if: ${{success()}} || ${{failure()}}
      with:
        name: wget-${{env.mingw}}-${{env.build_type}}_${{env.SHA}}
        path: |
          ${{env.CDir}}/src/wget-${{matrix.ftype}}.exe
    - name: Get version number
      run: |
        VERSION=$(cat ${{env.CDir}}/.version)
        echo "wget_VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: wget-${{ env.wget_VERSION }}
        allowUpdates: true
        artifacts: "${{env.CDir}}/src/wget-${{matrix.ftype}}.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
